### ISSUE TITLE
Parse the Markdown source code, please.

### ISSUE THREAD

**Issue by jizhipen** [carlrobertoh/CodeGPT#50] opened 2023-03-21 08:56 UTC
This is a fantastic plugin. It would be even better if it could parse Markdown instead of outputting the source code.

**Comment by carlrobertoh** [comment] 2023-03-21 10:36
Hi, I'll try to get to it as soon as I find some time.

Closing this since it's a duplicate of #39

**Closed by carlrobertoh** 2023-03-21 10:36 UTC
