### ISSUE TITLE
Commit message generation doesn't actually send git diff to LLM

### ISSUE THREAD

**Issue by Bikkies** [carlrobertoh/CodeGPT#418] opened 2024-03-21 03:43 UTC
### What happened?

When using the "Generate Message" button in the commit interface, only the prompt to generate the message is sent to the LLM, and none of the actual git diff. This means that the LLM outputs a completely made up list of changes.

### Relevant log output or stack trace

```shell
13:10:58-614334 INFO     PROMPT=
<｜begin▁of▁sentence｜>Write a short and descriptive git commit message for the following git diff.
Use imperative mood, present tense, active voice and verbs.
Your entire response will be passed directly into git commit.### Response:


Output generated in 3.84 seconds (26.05 tokens/s, 100 tokens, context 62, seed 2126101025)
```

### Steps to reproduce

Using PHPStorm 2023.3.5 and an openai-compatible model provider with logging that allows you to see the raw prompt to the LLM. 

Make changes to the code and ensure there are changes in the git diff.

Open the commit interface and click the "Generate Message" button.

Observe that only the prompt to generate the message is sent to the LLM along with no git diff.

Observe that the response is completely made up as the LLM has no context of the actual git diff

### CodeGPT version

2.5.1

### Operating System

Windows

**Comment by a8b7** [comment] 2024-03-22 02:13
I have the same problem

**Comment by razisam** [comment] 2024-03-22 12:49
same here: https://github.com/carlrobertoh/CodeGPT/issues/390#issuecomment-2009208391

**Comment by rwese** [comment] 2024-04-04 18:37
I wanted to fix this, since i use this feature a lot, it seems it is already fixed in the current master.

**Comment by carlrobertoh** [comment] 2024-04-06 11:40
I will release the new stuff sometime early next week.

**Comment by rwese** [comment] 2024-04-14 16:50
@carlrobertoh update, the issue is reproducible, on main, using the gpt-4 turbo (128k) model.

If I find some time I'll try and look into it.

**Closed** 2024-05-21 23:29 UTC
Labels: bug
