### ISSUE TITLE
Azure OpenAI Service doesn't see API Key

### ISSUE THREAD

**Issue by mpushkin** [carlrobertoh/CodeGPT#376] opened 2024-02-19 17:20 UTC
### What happened?

I'm using Azure OpenAI service, it was working fine several days ago, now it doesn't, likely after latest update (to 2.3.0).
For any request it says API Key is not provided even though it's there.

![CleanShot 2024-02-19 at 18 14 38@2x](https://github.com/carlrobertoh/CodeGPT/assets/4459516/1bbc816b-7556-4f70-b891-612fe098b57f)

### Steps to reproduce

Send any request with Azure OpenAI service.

### CodeGPT version

2.3.0

### Operating System

macOS

**Comment by carlrobertoh** [comment] 2024-02-19 20:13
Hey,

This is a duplicate of [#375](https://github.com/carlrobertoh/CodeGPT/issues/375), and the new version will be available in less than 48h. In the meantime, you could set a dummy value for Active Directory token, which should allow you to bypass it.

**Comment by razisam** [comment] 2024-02-20 12:33
i can confirm issue! thanks for fixing it!

**Closed** 2024-02-27 10:44 UTC
Labels: bug
