### ISSUE TITLE
Can the language of these questions be changed to my local language instead of fixed English?

### ISSUE THREAD

**Issue by MangerLe** [carlrobertoh/CodeGPT#24] opened 2023-03-08 03:24 UTC
![image](https://user-images.githubusercontent.com/51878514/223611628-47d37a4d-a54e-4fcc-8c49-71755ccef5be.png)
![image](https://user-images.githubusercontent.com/51878514/223611684-8a03c025-06aa-4a17-bb8d-e163d982781f.png)

**Comment by MangerLe** [comment] 2023-03-08 03:26
I'm talking, of course, about the language in which he asked, because the language in which the question was asked, the language in which the GPT would answer.

**Comment by rangzen** [comment] 2023-03-08 04:58
Hello @MangerLe, there are already some issues and discussions on this topic, see #20 and #22.

**Comment by carlrobertoh** [comment] 2023-03-08 10:46
Closing this, since it's a duplicate of #22

**Closed** 2023-03-08 10:46 UTC
