### ISSUE TITLE
Unable to connect with Azure openAI

### ISSUE THREAD

**Issue by mrumeshkumarbs** [carlrobertoh/CodeGPT#346] opened 2024-01-30 11:27 UTC
### What happened?

![2024-01-30 16_54_22-IDE Internal Errors](https://github.com/carlrobertoh/CodeGPT/assets/82029044/6d7343c6-307d-43c5-93c1-483b8fa388ea)

Hi Team,

I am getting error while connecting to the Azure OpenAI using API Key

Error:

Resource not found

java.lang.RuntimeException
	at ee.carlrobert.llm.completion.CompletionEventSourceListener.onFailure(CompletionEventSourceListener.java:114)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

### Steps to reproduce

Adding Azure openAI api details. and after trying to start any chat.

### CodeGPT version

CodeGPT 2.2.12

### Operating System

Windows

**Comment by elabbarw** [comment] 2024-02-01 21:07
I get unknown API response using api-key and azure ad: 
![image](https://github.com/carlrobertoh/CodeGPT/assets/70503629/4affd473-e73c-4982-8f8a-25d41ed0bfc9)
I can confirm that my token is working.

**Comment by elabbarw** [comment] 2024-02-01 21:27
I'm having similar trouble: 

Unknown API response. Code: 200, Body: 

com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4990)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4892)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at ee.carlrobert.llm.client.azure.AzureClient$1.getErrorDetails(AzureClient.java:101)
	at ee.carlrobert.llm.completion.CompletionEventSourceListener.onFailure(CompletionEventSourceListener.java:108)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:78)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by elabbarw** [comment] 2024-02-01 21:29
> ### What happened?
> ![2024-01-30 16_54_22-IDE Internal Errors](https://private-user-images.githubusercontent.com/82029044/300788535-6d7343c6-307d-43c5-93c1-483b8fa388ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjMyNDMsIm5iZiI6MTcwNjgyMjk0MywicGF0aCI6Ii84MjAyOTA0NC8zMDA3ODg1MzUtNmQ3MzQzYzYtMzA3ZC00M2M1LTkzYzEtNDgzYjhmYTM4OGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIxMjkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYzU2YmM5MjdjNDIyNzgwMjRmMWVmODIwMjMyZDRkMjJiMzExMzNiMzUzN2Q2NjRjODA3ZThmODhkMGFhZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g18u_lLNTTU8RCwoi1I4Qg-OIyf01Gyi3x3JNQPgoK8)
> 
> Hi Team,
> 
> I am getting error while connecting to the Azure OpenAI using API Key
> 
> Error:
> 
> Resource not found
> 
> java.lang.RuntimeException at ee.carlrobert.llm.completion.CompletionEventSourceListener.onFailure(CompletionEventSourceListener.java:114) at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52) at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46) at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.lang.Thread.run(Thread.java:840)
> 
> ### Relevant log output or stack trace
> _No response_
> 
> ### Steps to reproduce
> Adding Azure openAI api details. and after trying to start any chat.
> 
> ### CodeGPT version
> CodeGPT 2.2.12
> 
> ### Operating System
> Windows

Can you share the settings? Maybe i can help :)

**Comment by carlrobertoh** [comment] 2024-02-02 14:01
Could someone please copy-paste the exact SSE responses for both versions? I can see the non-stream response in their Swagger documentation, but I can't find anything with `"stream": true`.

**Comment by carlrobertoh** [comment] 2024-02-02 14:26
This is the cURL request that CodeGPT makes, it would be nice if someone could compare the behaviour using different API versions.

```bash
curl -X POST "https://my_resource_name.openai.azure.com/openai/deployments/my_deployment_id/chat/completions?api-version=2023-05-15" \
     -H "api-key: MY_API_KEY" \
     -H "X-LLM-Application-Tag: codegpt" \
     -H "Accept: text/event-stream" \
     -H "Content-Type: application/json; charset=utf-8" \
     -d '{"messages":[{"role":"system","content":"CODEGPT_SYSTEM_PROMPT"},{"role":"user","content":"Hi there!"}],"temperature":0.1,"stream":true,"max_tokens":1000,"frequency_penalty":0.0,"presence_penalty":0.6}'
```

**Comment by mkotzerke** [comment] 2024-02-02 15:00
I had similar issues. 
Solution for me was : 

1. remove trailing whitespaces in the plugin config for ressource nam,deployment id,... which caused the request to fail
2. to not use an preview AI-Version, "2023-05-15" worked for me.

After that it worked perfectly :)

@carlrobertoh  I think it would make sense to automatically strip whitespaces since its a hard to track down error.

**Comment by jsanko9** [comment] 2024-02-16 06:18
Having same issue with 2.3.0 too. Tried API version "2023-05-15" but it didn't help.

**Comment by carlrobertoh** [comment] 2024-02-26 10:41
I will be releasing a custom OpenAI-compatible service configuration in the upcoming days. Hopefully it will solve most of the problems.

https://github.com/carlrobertoh/CodeGPT/pull/383

**Comment by carlrobertoh** [comment] 2024-02-26 13:50
Version 2.4.0 is now publicly available, providing the option to configure custom OpenAI-compatible services.

Please let me know if it helps.

**Comment by razisam** [comment] 2024-02-26 14:32
> Version 2.4.0 is now publicly available, providing the option to configure custom OpenAI-compatible services.
> 
> Please let me know if it helps.

thanks, new UI is working fine for me but using "2024-02-15-preview" as api-version does not work.

![image](https://github.com/carlrobertoh/CodeGPT/assets/59828907/651ec981-c9ff-4165-ab74-9a98dba29a40)

**Comment by razisam** [comment] 2024-02-26 15:31
> Version 2.4.0 is now publicly available, providing the option to configure custom OpenAI-compatible services.
> 
> Please let me know if it helps.

the new ui is working fine, but using a "preview" version does not work yet

```
2024-02-26 10:17:44,785 [2577927]   INFO - STDERR - [OkHttp https://XXXXXX.openai.azure.com/...] ERROR ee.carlrobert.llm.completion.CompletionEventSourceListener - Could not serialize error response
2024-02-26 10:17:44,786 [2577928]   INFO - STDERR - java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
2024-02-26 10:17:44,786 [2577928]   INFO - STDERR - 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
2024-02-26 10:17:44,786 [2577928]   INFO - STDERR - 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
2024-02-26 10:17:44,786 [2577928]   INFO - STDERR - 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
2024-02-26 10:17:44,786 [2577928]   INFO - STDERR - 	at java.base/java.util.Objects.checkIndex(Objects.java:361)
2024-02-26 10:17:44,786 [2577928]   INFO - STDERR - 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
2024-02-26 10:17:44,786 [2577928]   INFO - STDERR - 	at ee.carlrobert.llm.client.openai.completion.OpenAIChatCompletionEventSourceListener.getMessage(OpenAIChatCompletionEventSourceListener.java:19)
2024-02-26 10:17:44,786 [2577928]   INFO - STDERR - 	at ee.carlrobert.llm.client.openai.completion.OpenAIChatCompletionEventSourceListener.getMessage(OpenAIChatCompletionEventSourceListener.java:9)
2024-02-26 10:17:44,787 [2577929]   INFO - STDERR - 	at ee.carlrobert.llm.completion.CompletionEventSourceListener.onEvent(CompletionEventSourceListener.java:63)
2024-02-26 10:17:44,787 [2577929]   INFO - STDERR - 	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
2024-02-26 10:17:44,787 [2577929]   INFO - STDERR - 	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
2024-02-26 10:17:44,787 [2577929]   INFO - STDERR - 	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
2024-02-26 10:17:44,787 [2577929]   INFO - STDERR - 	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
2024-02-26 10:17:44,787 [2577929]   INFO - STDERR - 	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
2024-02-26 10:17:44,787 [2577929]   INFO - STDERR - 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
2024-02-26 10:17:44,787 [2577929]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-02-26 10:17:44,787 [2577929]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-02-26 10:17:44,787 [2577929]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-02-26 10:17:44,790 [2577932] SEVERE - #ee.carlrobert.codegpt.toolwindow.chat.ToolWindowCompletionResponseEventListener - Unknown API response. Code: 200, Body: 
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4990)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4892)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at ee.carlrobert.llm.client.azure.AzureClient$1.getErrorDetails(AzureClient.java:100)
	at ee.carlrobert.llm.completion.CompletionEventSourceListener.onFailure(CompletionEventSourceListener.java:108)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:78)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-02-26 10:17:44,790 [2577932] SEVERE - #ee.carlrobert.codegpt.toolwindow.chat.ToolWindowCompletionResponseEventListener - IntelliJ IDEA 2024.1 EAP  Build #IU-241.13688.18
2024-02-26 10:17:44,790 [2577932] SEVERE - #ee.carlrobert.codegpt.toolwindow.chat.ToolWindowCompletionResponseEventListener - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.

```

**Comment by carlrobertoh** [comment] 2024-02-26 15:57
@razisam I uploaded a pre-release to fix the `IndexOutOfBoundsException`. Could you please try to install it manually and see if it makes any difference?

https://github.com/carlrobertoh/CodeGPT/releases/tag/2.4.1-pre

<img width="692" alt="Screenshot 2024-02-26 at 17 55 22" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/07abf69c-68a6-4f34-ad8a-1b768716e8ea">

**Comment by jimmyland22** [comment] 2024-02-27 00:54
I updated it to 2.4.1 and changed the API version to 2024-02-15-preview, seems to work.

**Comment by razisam** [comment] 2024-02-27 09:57
> @razisam I uploaded a pre-release to fix the `IndexOutOfBoundsException`. Could you please try to install it manually and see if it makes any difference?
> 
> https://github.com/carlrobertoh/CodeGPT/releases/tag/2.4.1-pre
> 
> <img alt="Screenshot 2024-02-26 at 17 55 22" width="692" src="https://private-user-images.githubusercontent.com/15891408/307858909-07abf69c-68a6-4f34-ad8a-1b768716e8ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjgxMjgsIm5iZiI6MTcwOTAyNzgyOCwicGF0aCI6Ii8xNTg5MTQwOC8zMDc4NTg5MDktMDdhYmY2OWMtNjhhNi00ZjM0LWFkOGEtMWI3Njg3MTZlOGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA5NTcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMjJkMTExMDljOTc3N2FkOWYwYjI0NzRmMDQ3MDk4NWE3Y2UwNmJkMmJjYmFhMjg0OTU3OWRlOGEyZTc5ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FpskRnDk4cA3nXCGv2zHp1zxvZ4nz4DNdTtaZh51Ohw">

works for me, too!

**Comment by vatorio** [comment] 2024-03-01 05:28
how change  the API version to 2024-02-15-preview, show please

**Comment by carlrobertoh** [comment] 2024-04-23 11:40
Should be fixed in the latest version. Please reopen the ticket if it's still reproducible.

@vatorio There's an individual field for the API version in the Azure Service panel. Another option is to configure everything manually in the Custom OpenAI Service -> Select the Azure OpenAI Template -> Modify the URL.

**Closed by carlrobertoh** 2024-04-23 11:40 UTC
Labels: bug
