### ISSUE TITLE
codeGPT doesn't support multiple projects chat windows

### ISSUE THREAD

**Issue by chatGPTxx** [carlrobertoh/CodeGPT#209] opened 2023-09-18 12:36 UTC
### What happened?

When open multiple projects, the chats always go to the first project window.  
It happens for both IntelliJ and Pycharm. 

### Relevant log output or stack trace

```shell
don't see any error messages, difficult to debug as well.
```

### Steps to reproduce

1. Install plugin
2. open two projects
3. chat with codeGPT in first project
4. chat with codeGPT in second project, it goes to first project chat window

### CodeGPT version

2.0.6

### Operating System

Windows

**Comment by carlrobertoh** [comment] 2023-09-27 21:21
Duplicate of [194](https://github.com/carlrobertoh/CodeGPT/issues/194)

**Closed by carlrobertoh** 2023-09-27 21:21 UTC
Labels: bug
