### ISSUE TITLE
Azure OpenAI broken

### ISSUE THREAD

**Issue by olafgeibig** [carlrobertoh/CodeGPT#232] opened 2023-10-11 13:36 UTC
### What happened?

Responds always with ```openai.azure.com: nodename nor servname provided, or not known```

Substituting the %s with the actual values seems to produce a wrong HTTP request.

It was working previously with the same configuration, I think two weeks ago. Other tools I'm using are still working with the same Azure deployment. cURL is working:
```
curl "https://XXX.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2023-05-15" \
  -H "Content-Type: application/json" \
  -H "api-key: ZZZ" \
  -d "{
  \"messages\": [{\"role\":\"user\",\"content\":\"Hi\"}],
  \"max_tokens\": 800,
  \"temperature\": 0.0,
  \"frequency_penalty\": 0,
  \"presence_penalty\": 0,
  \"top_p\": 0.95,
  \"stop\": null
}"
{"id":"chatcmpl-88TIwpbMfYJIH62QI1YSrLT02wKlB","object":"chat.completion","created":1697029962,"model":"gpt-4","choices":[{"index":0,"finish_reason":"stop","message":{"role":"assistant","content":"Hello! How can I assist you today?"}}],"usage":{"completion_tokens":9,"prompt_tokens":8,"total_tokens":17}}
```
My old plugin config that was working previously and now produces the error above:
![Screenshot 2023-10-11 at 15 22 53](https://github.com/carlrobertoh/CodeGPT/assets/295644/fda10bc0-547b-4c7f-aad7-895f4005ec82)

## Workaround
Replace %s with the actual values. In my case resource name, deployment ID and API version
![Screenshot 2023-10-11 at 15 40 40](https://github.com/carlrobertoh/CodeGPT/assets/295644/ef9d5f8d-0f5f-428c-b64b-a8d12b0a83ed)

Then it works properly

### Steps to reproduce

1. Configure to use Azure OpenAI according to documentation
2. Use chat

### CodeGPT version

2.5.1

### Operating System

macOS

**Comment by darkakushi** [comment] 2023-10-11 13:56
Same issue here, but the workaorund seems not work in my case:

![image](https://github.com/carlrobertoh/CodeGPT/assets/11303220/029ec487-7946-4468-bc6a-6c5f37d36c79)

**Comment by carlrobertoh** [comment] 2023-10-11 14:06
Thank you for the cURL request!
Unfortunately, I don't have access to Azure services, so I can't test the actual flow. However, I will try to find any differences between the cURL request and what CodeGPT is sending.

**Comment by darkakushi** [comment] 2023-10-11 15:23
Maybe this could help:
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions

**Comment by darkakushi** [comment] 2023-11-07 12:31
Still not working for me:

![image](https://github.com/carlrobertoh/CodeGPT/assets/11303220/faabf257-c303-45f6-9eb8-39a6abee1fa5)

![image](https://github.com/carlrobertoh/CodeGPT/assets/11303220/ac895056-7d84-4861-8a6b-c65f964dce18)

**Comment by carlrobertoh** [comment] 2023-11-07 16:10
Could someone provide me with an example response for this version, please?

**Comment by darkakushi** [comment] 2023-11-07 17:17
This is the raw request:

{
  "messages": [{"role":"system","content":"You are an AI assistant that helps people find information."},{"role":"user","content":"Hello how are you?"}],
  "max_tokens": 800,
  "temperature": 0.7,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "top_p": 0.95,
  "stop": null
}

this is the response

**Comment by carlrobertoh** [comment] 2023-11-07 19:09
Thank you! 
Is the `choices` response model the same for streaming as well? That is, when sending an additional `stream: true` parameter to the request body.

**Comment by darkakushi** [comment] 2023-11-07 21:05
it seems to be same structure:
{
    "id": "chatcmpl-8INTQ2ThEvYhlhS0xdMiM67bsJxYq",
    "object": "chat.completion.chunk",
    "created": 1699390828,
    "model": "gpt-4",
    "choices": [
        {
            "index": 0,
            "finish_reason": null,
            "delta": {
                "content": " can"
            },
            "content_filter_results": {
                "hate": {
                    "filtered": false,
                    "severity": "safe"
                },
                "self_harm": {
                    "filtered": false,
                    "severity": "safe"
                },
                "sexual": {
                    "filtered": false,
                    "severity": "safe"
                },
                "violence": {
                    "filtered": false,
                    "severity": "safe"
                }
            }
        }
    ],
    "usage": null
}

this is one of the many responses adding stream: true.

![image](https://github.com/carlrobertoh/CodeGPT/assets/11303220/36344e62-7a0d-480e-a173-03d30412f918)

**Comment by carlrobertoh** [comment] 2023-11-08 17:00
There is a difference in properties between `delta` and `message`, and in theory, this should already be supported.
Unfortunately, I am unable to reproduce the issue locally, nor can I debug it because I don't have access to Azure service.

**Comment by darkakushi** [comment] 2023-11-16 08:33
Hi, with new version, now i can see the details of the issue:

![image](https://github.com/carlrobertoh/CodeGPT/assets/11303220/0cba763c-7ab1-4b7c-96bd-c93e75de4ab3)

  Unknown API response. Code: 200, Body: 
  
  com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
at [Source: (String)""; line: 1, column: 0]
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4916)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4818)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
at ee.carlrobert.llm.client.azure.AzureClient$1.getErrorDetails(AzureClient.java:90)
at ee.carlrobert.llm.completion.CompletionEventSourceListener.onFailure(CompletionEventSourceListener.java:107)
at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:78)
at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by darkakushi** [comment] 2024-02-27 19:34
It work very well, thanks a lot.

**Comment by superbillen** [comment] 2024-04-11 12:33
I just cant get this to connect, are any of you able to help me out? i have tried the last 3 days getting this to work. My Azure webapp works perfectly but cant get this to work and your thread are the only one i found with users using the Azure Open Ai modul

**Comment by darkakushi** [comment] 2024-04-15 07:25
> I just cant get this to connect, are any of you able to help me out? i have tried the last 3 days getting this to work. My Azure webapp works perfectly but cant get this to work and your thread are the only one i found with users using the Azure Open Ai modul

I don't know how to help you, with the plugin last update, putting the configuration as the image above shows, the plugin start to work kind immediatly

**Comment by carlrobertoh** [comment] 2024-04-23 11:41
Should be fixed in the latest version. Please reopen the ticket if it's still reproducible.

**Closed by carlrobertoh** 2024-04-23 11:41 UTC
Labels: bug
