### ISSUE TITLE
"Something went wrong"

### ISSUE THREAD

**Issue by acheese** [carlrobertoh/CodeGPT#76] opened 2023-04-05 05:31 UTC
I cannot get this plugin to work. I always get the error "Something went wrong. Please try again later".
![Screenshot 2023-04-05 073102](https://user-images.githubusercontent.com/4725349/229989422-a53ce566-fe34-47e9-917c-507eb44b5409.png)

**Comment by carlrobertoh** [comment] 2023-04-05 09:25
Hi

Could you try hitting the API directly via cURL?

```curl
curl https://api.openai.com/v1/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -d '{
  "model": "text-davinci-003",
  "prompt": "Say hello in 3 different languages.",
  "temperature": 0.9,
  "max_tokens": 150,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0.6
}'
```

**Comment by acheese** [comment] 2023-04-06 05:57
I tried this and got a good response:

{"id":"cmpl-72CtuDg0zlrfKHzFSLpS1Mr8rMo6E","object":"text_completion","created":1680760602,"model":"text-davinci-003","choices":[{"text":"\n\n1. Bonjour (French)\n2. Hola (Spanish)\n3. Ni hao (Mandarin Chinese)","index":0,"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":7,"completion_tokens":29,"total_tokens":36}}

**Comment by carlrobertoh** [comment] 2023-04-08 15:49
@acheese without any logs, I'm unable to find the cause of the issue
@magicpot73 The billing info started failing recently because OpenAI changed their security policy. This request will be removed in the next release. Also it seems like you need to add the certificate to your truststore file that's used by the JVM.
https://stackoverflow.com/questions/9619030/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatore/9619478#9619478

I'm going to add more logging in the next release, so I can track the issue better.

**Comment by magicpot73** [comment] 2023-04-10 23:39
@carlrobertoh 
Thank you, I'll give it a try. I hope that by logging more information about this issue, we can improve our ability to trace it.

**Comment by magicpot73** [comment] 2023-04-11 02:03
@carlrobertoh 
For adding information,
I also add provided certificate to my Jetbrains runtime truststore. The problem was  resolved.
Here is I was added security store path. (Windows OS and IDE was installed by Jetbrains Toolbox)
{HOME}\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.6008.13\jbr\lib\security

The plugin was not using "$JAVA_HOME\lib\security\cacerts".
This is my environment case. (Default Intellj IDE launches)

**Comment by acheese** [comment] 2023-04-11 08:30
Which certificate are you talking about and where/how do I fetch it? Thanks Andy

**Comment by carlrobertoh** [comment] 2023-04-11 20:34
@acheese Are you seeing any error logs?

**Comment by acheese** [comment] 2023-04-12 05:44
I am not sure which log you are referring to.
I do see this message in the IDE idea.log :
2023-04-12 07:38:58,817 [  12039]   INFO - STDERR - [OkHttp https://api.openai.com/...] ERROR ee.carlrobert.openai.client.billing.BillingResponseCallback - Unable to retrieve billing info

I also find it strange that there is a separate proxy menu for the plugin when the IDE has its  own proxy settings. Could this be the problem? I have no problems with any other plugins. How do I tell the plugin to use the IDE proxy settings? I don't see an option for this or a need for this as this should be the default.

**Comment by acheese** [comment] 2023-04-12 05:46
[idea.log](https://github.com/carlrobertoh/CodeGPT/files/11207591/idea.log)

**Comment by acheese** [comment] 2023-04-13 07:51
Where do I find the certficate for the plugin?

**Comment by carlrobertoh** [comment] 2023-04-14 10:30
@acheese Try downloading the cert from the OpenAI website (https://apisero.com/how-to-resolve-pkix-path-building-failed-unable-to-find-valid-certification-path-to-requested-target-issue/) and then add it to your IDE JRE.

**Comment by acheese** [comment] 2023-04-17 07:47
The pathname is truncated in the log. Is there a setting in the plugin so that it can output the full pathname? so I can use this to fetch the certificate.

**Comment by carlrobertoh** [comment] 2023-04-17 10:49
I assume the certificate needs to be added to JetBrains runtime truststore.
Try adding it inside the IDE:
<img width="976" alt="Screen Shot 2023-04-17 at 11 45 15" src="https://user-images.githubusercontent.com/15891408/232462779-be807c5f-ba69-4362-b611-9d7d2866819a.png">

Or locate the cacerts manually as @magicpot73 described.

**Comment by acheese** [comment] 2023-04-17 12:14
Added the certificate using both methods but still same error message generated in idea.log

**Comment by carlrobertoh** [comment] 2023-04-20 11:20
@acheese Sorry, I'm unable to reproduce it locally. Would you mind sharing me the proxy settings via email?

**Comment by acheese** [comment] 2023-04-20 11:28
I do not know what to set the plugin proxy settings to so I have left them
as installed  (see the attached pictures).

**Comment by CheerMan1** [comment] 2023-04-25 08:10
Hi, I have same problem.

**Comment by carlrobertoh** [comment] 2023-04-25 10:43
The error indicates that the server uses a self-signed certificate that is not signed by a Certificate Authority. 

Again, I think there's not much I can do on my side to fix the error for you.
You need to add the certificate to the internal intellij JRE:
```
keytool -noprompt -keystore ~/.local/share/JetBrains/Toolbox/cacerts -import -trustcacerts -file /usr/local/share/ca-certificates/CERT.crt -alias uniq name -storepass UNIQUE_PASSWORD
```

Follow these steps below:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000094584/comments/115000405564

**Closed** 2023-06-27 09:04 UTC
