### ISSUE TITLE
Generate commit button is inactive when commit dialog is non-modal

### ISSUE THREAD

**Issue by tkosman-idt** [carlrobertoh/CodeGPT#443] opened 2024-04-09 14:53 UTC
### What happened?

If I switch to modal dialog, I can press Cmd+K and the Generate Commit button will be active.
If I switch back to non-modal dialog, I press Cmd+0 and the Generate Commit button is inactive.

### CodeGPT version

2.5.1

### Operating System

macOS

**Comment by tkosman-idt** [comment] 2024-04-11 09:26
<img width="564" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/119938389/b792d41e-f157-46a5-9a4c-1db1407d1297">
<img width="987" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/119938389/6ffc5bb8-bf82-44f0-8aba-d17c11d4a5e7">
<img width="411" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/119938389/44ee474c-215d-41de-b714-95035550a292">
I don't understand what you mean with this before. But As you see – in a modal version I have the active button.

**Comment by carlrobertoh** [comment] 2024-04-11 09:34
It looks like the non-dialog view doesn't respect the selection of unversioned files, which is used to control the icon button's enabled/disabled state.

**Comment by tkosman-idt** [comment] 2024-04-11 09:40
<img width="580" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/119938389/c715086c-b482-4f38-968d-956788c1e3b8">

**Comment by reneleonhardt** [comment] 2024-04-12 06:10
Could it be that the disabled icon has a tooltip `Credentials not provided`? What service is selected?
Can you try again with Llama C/C++?

**Comment by tkosman-idt** [comment] 2024-04-14 10:57
I use it with llama. Because I can't share my code with third-party vendors like Git Hub.

**Comment by tkosman-idt** [comment] 2024-04-14 11:01
I didn't change anything. Only restarted my computer 2 days ago. Now, when I go to check the tooltip, the button is active. So the bug is missed. I have no idea how to recreate it.

**Comment by carlrobertoh** [comment] 2024-04-23 11:36
Should be fixed in the latest version. Please reopen the ticket if it's still reproducible.

**Closed by carlrobertoh** 2024-04-23 11:36 UTC
Labels: bug
