### ISSUE TITLE
 input box

### ISSUE THREAD

**Issue by fatebugs** [carlrobertoh/CodeGPT#62] opened 2023-03-25 14:25 UTC
Is the input box too narrow, and the input box will get smaller and smaller at some point?
![image](https://user-images.githubusercontent.com/65278566/227723109-20b4c5fd-b275-4c73-af37-6d3fb6ab4e25.png)

**Comment by carlrobertoh** [comment] 2023-03-29 11:06
Not sure I understand the question, could you be more specific?

**Comment by fantom0005** [comment] 2023-04-02 07:01
I think that @fatebugs mean that we can't to change the input size when we're chatting with GPT

<img width="768" alt="image" src="https://user-images.githubusercontent.com/3921689/229337713-b5f60578-c57d-4251-bbf7-1b5322d61534.png">

<img width="792" alt="image" src="https://user-images.githubusercontent.com/3921689/229337721-1f2549d9-f03d-4383-bbdd-182737c5d434.png">

It is uncomfortable when you write a long prompt

@carlrobertoh

**Comment by carlrobertoh** [comment] 2023-04-08 18:52
Closing this as a duplicate of #77

**Closed by carlrobertoh** 2023-04-08 18:52 UTC
